---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - wordpress.cloud104.io
  resources:
  - wordpresssites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wordpress.cloud104.io
  resources:
  - wordpresssites/finalizers
  verbs:
  - update
- apiGroups:
  - wordpress.cloud104.io
  resources:
  - wordpresssites/status
  verbs:
  - get
  - patch
  - update
