apiVersion: wordpress.cloud104.io/v1alpha1
kind: WordpressSite
metadata:
  name: meu-blog
spec:
  domain: meu-blog.francis.tcloud-devops.cloudtotvs.com.br
  ingressClassName: nginx
  ingressAnnotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    enabled: true
    issuerName: letsencrypt-prod
    issuerKind: ClusterIssuer
  wordpress:
    replicas: 1
  database:
    name: wordpress
    user: wordpress